<h2>Categorias</h2>

<table class="table table-hover">
    <tr  align="center" class="active">
        <th>#</th>
        <th>Nome</th>
        <th>Editar</th>
        <th>Excluir</th>
    </tr>
    <tbody>
        <tr>
            <td>1</td>
            <td>Romance</td>
            <td><button type="button" class="btn btn-small btn-xs"><span class="fa fa-edit"></span> Editar</button></td>
            <td><button type="button" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Excluir</button></td>
        </tr>
    </tbody>
</table>
<hr>
<button type="button" class="btn btn-primary "><span class="fa fa-book"></span> Nova Categoria</button>
