<h1>Categorias</h1>


<table class="table table-hover">
    <tr class="active block">
        <th>#</th>
        <th>Nome</th>
        <th>Editar</th>
        <th>Excluir</th>
    </tr>
    <tbody>
        <tr>
            <td>1</td>
            <td>Romance</td>
            <td><a class="glyphicon glyphicon-edit"></a></td>
            <td><a class="glyphicon glyphicon-trash"></a></td>
        </tr>
        
        <tr>
            <td>2</td>
            <td>Aventura</td>
            <td><a class="glyphicon glyphicon-edit"></a></td>
            <td><a class="glyphicon glyphicon-trash"></a></td>
        </tr>
        
        <tr>
            <td>3</td>
            <td>Drama</td>
            <td><a class="glyphicon glyphicon-edit block"></a></td>
            <td><a class="glyphicon glyphicon-trash block"></a></td>
        </tr>
    </tbody>
</table>