<h3>Categorias</h3>
<hr />

<table class="table table-hover">
    <thead>
        <tr class="active">
            <th>#</th>
            <th>Nome</th>
            <th>Editar</th>
            <th>Deletar</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>1</td>
            <td>Romance</td>
            <td><i class="glyphicon glyphicon-edit"></i> Editar</td>
            <td><a href="/livraria"><i class="glyphicon glyphicon-trash"></i> Deletar</a></td>
        </tr>
    </tbody>
</table> 